### PR TITLE
Support for SPA on the same domain

### PR DESCRIPTION
**Pull request by RusTigra**
# Support for SPA on the same domain

## Summary 
Create ability to use Gatekeeper with some services with Bearer Auth and with SPA with cookies at the same time.
SPA must be located on the same domain to avoid cross-site references and cookies.

## Type

[] Bug fix
[] Feature request
[x] Enhancement
[] Docs

## Why?
We want to use one gateway (gatekeeper) and one auth-service (keycloak) to many services in private zone.
There are two type of clients:
1. Other services which can be clients for Keycloak itself and use bearer token authentication
2. SPA (admin UI) which can't store securities but only cookies

Because of services there is [no-redirects=true] option.
This is useful for SPA also. 

Because of AJAX (axois, XHR) requests to API. It's a very uncofortable situation to obtain 303-redirect and HTML with login page as result of request accepting JSON.
Thats why SPA catch 401 error in case of unauthentificated request. Then it get "Location" header contains path to authorization endpoint and make "full" redirect. This header is used to free SPA from dublicate this GK-setting (oauth-uri)
While processing this request GK would store "Referer" header (with page of SPA application) as "return url" after full auth-flow.
This value stored only in case of equality of domains for SPA (referer header) and API (request url).

**NB** this workflow is applied only for [no-redirects=true]

## Requirements
--

## How to try it?
--

## Documentation
 --

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.

### CODE REVIEW

**Comment by p53** [comment]
hi, thanks for submiting! will have a look, understanded your use case.

**Comment by RusTigra** [comment]
I think it would be better to describe our case with examples.
We have private segment with APIs, services, databases, message brokers, etc.
Inner communications are fully trusted. But there are some outer requests to some endpoints.
We don't want to implement Auth in every part of this segment and make inner communications more complex.
Outer requests can be:
1. Some service from an another segment - no matter what is it and where is it but this is robot
2. Admin UI - some SPA, i.e. requests come from some browser located somewhere in Internet
3. There can be another SPA - for example for support, readonly access, etc.

We've chosen Keyckoak as Auth server and Gatekeeper as Auth gateway closing whole segment.

External routes to allowed endpoints are (for example)
http://domain/api1/someresource
http://domain/api2/someresource
These APIs are beyond Gatekeeper.

SPAs address is (we can place it in the same domain)
http://domain/spa1/somepage
http://domain/spa2/somepage

When some of external services calls http://domain/api1/someresource it must apply header with Bearer token. This are nothing unusual, service can store securities and communicate with Keyckoak to obtain token.
But SPA can't. And we need to authenticate user. So...

Brower go to page http://domain/spa1/somepage and on page make AJAX call to http://domain/api1/someresource
If we set [no-redirects=false] the result would be:
Resource data (json) if user was authenticated
Or
Keycloak login page (HTML) if was not authenticated
This is not very clear and easy to process. And this is unacceptable for services (401 error is much better)
We need to redirect whole browser from SPA to Keycloak login page and return to SPA. 

Thats why we set  [no-redirects=true]
Services get data or 401 - OK, this is problem of service to get correct token
SPA get data or 401 - OK, this is very easy to process

Let's describe case of "SPA get 401 error on AJAX call":
We need to redirect browser to /oauth/authorize endpoint for user authentication. 
This route belongs to Gatekeeper and can be modified (oauth-uri option)
That's why we place it in header Location of 401 error response.
It's not a good idea to fix it in SPA1 configuration (or hardcode...)

SPA catch 401 error and make redirect to authorize endpoint - starting oauth login process.
Gatekeeper redirects browser to Keyckoak login page, user logined, Keyckoak redirects browser to callback URL of Gatekeeper. 
As the result of this process we would like to land on http://domain/spa1/somepage page (as start page of all process)
But Gatekeeper knows nothing about this page. It returns to http://domain (or some API route in case of [no-redirects = false])
It's not a problem if we have single SPA. But we have two in example.
Main idea: when SPA redirects browser to authorize endpoint this "start url" is placed to Referer header of request.
We can read and store this url just like [no-redirects = false]. And check domains of reference header (SPA location) and request (Gatekeeper/API location)
Then we can use cookies to store access token (SPA and API are on the samedomain)

PS
I understand the case "SPA and APIs are on different domains" - it's very difficult... And we don't need this.

SPA and API can have "same site" location. http://domain/spa and http://api.domain
Flow can be the same. But I don't know simple way to check this. And we don't use this due to company policy.

PPS
I see Go first time two days ago. My code can be not good enough. Sorry :-))

**Comment by p53** [comment]
@RusTigra i can tell you how i've done it, but i've done it with 2 gogatekeepers (one for SPA - no-redirects=false and one for api - no-redirects=true) with proxy before them. When user comes first time it goes to gogatekeeper SPA with no-redirects=false => is redirected to keycloak => autheticated => it creates cookies (i set cookie to httponly false) but i've also set to encrypt cookie (there is setting in gogatekeeper), then with js i fetched the cookie and sent to second gogatekeeper (the one for api, using credentials: include in js) => there is proxy before them to properly route to gogatekeepers according path

**Comment by RusTigra** [comment]
>user comes first time
Do you have SPA beneath gogatekeeper? And user must be authenticated to open SPA pages?

**Comment by p53** [comment]
@RusTigra yes SPA is behind gogatekeeper

**Comment by RusTigra** [comment]
This means dividing of functions.
One GK for create cookie and one GK for check it.

I don't understand what happens if user makes some actions which make AJAX calls to API without page reloading.
Access token would expire some time. What would happen then?

**Comment by p53** [comment]
@RusTigra you should have refresh token enabled

**Comment by RusTigra** [comment]
OK, I will try this

**Comment by RusTigra** [comment]
Thanks! :-)

**Pull request closed without merging**
