### PR TITLE
Keycloak 17+ compatibility changes

### PR DESCRIPTION
**Pull request by p53**
# Title

## Type

[] Bug fix
[] Feature request
[] Enhancement
[] Docs

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.

### CODE REVIEW

**Comment by brunocribeiro** [comment]
I must say, this is a pretty bad decision, [change the hard code path length](https://github.com/gogatekeeper/gatekeeper/pull/232/files#diff-0e426a43248661127a0c0ee115aef7a1093b635f8993b3f7ebb1dd9f05b8f249R687) is clearly not the fix to support deployments that either uses a custom context or not.

Now it doesn't work for deployments that configure a custom context using [`http-relative-path`](https://www.keycloak.org/server/all-config#_httptls) 😞

**Comment by p53** [comment]
@brunocribeiro problem is that Keycloak 17+ has more changes then just realm part, yes i know it doesn't support the old way but i don't want to have two different sets of tests or make them too much complicated just because of realm thing, in tests we are faking keycloak and so /auth thing is used every where there, i could change the code but i would logically need run tests against both and there are some additional changes, then i would need to cover all future changes on top of this which i think can be quite bad for maintaining and testing

**Comment by p53** [comment]
go-gatekeeper 2.0.0 would not work if released, keycloak has released new version 17 which remove /auth, it can be set with http relative path but i am not sure for how long there will be this option+i would need to adapt also other parts of code and hope they won't change some endpoint in newer versions, then probably adjustments would be hard or not possible, so i am quite afraid of maintaing backward compatibility with <17 releases

**Comment by ChristianCiach** [comment]
You don't need to maintain compatibility with keycloak < 17, but I think it would be better to maintain compatibility with supported keycloak versions that *do* have the `--http-relative-path` option. Why do you think this option will go away?

**Comment by p53** [comment]
One more thing only / and /auth will be supported as nerzal gocloak library which i am usimg supports only those two

**Pull request merged**
