### PR TITLE
[issues/21]: Use X-Forwarded-Proto proxy header to construct redirect…

### LINKED ISSUE #21: getRequestHostURL should support X-Forwarded-Proto
When determining `redirect_uri` to during a logout redirect request, gatekeeper does not use X-Forwarded-Proto. 

If gatekeeper is proxied behind something else that terminates TLS, the generated `redirect_uri` will be wrong, and may result in a broken logout flow.

### PR DESCRIPTION
**Pull request by OskarsPakers**
## Summary 

Fixes #21 

## Type

[x] Bug fix
[] Feature request
[] Enhancement
[] Docs

### CODE REVIEW

**Comment by p53** [comment]
@OskarsPakers i am working on it right now :), there was already issue there for this #21, but neverthless i made additional tests for LogoutHandler so i will add yours on top of it, thanks!

**Comment by OskarsPakers** [comment]
Sorry. Was browsing issues and the code and grabbed this tiny piece. Thank you for your effort!

**Comment by p53** [comment]
@OskarsPakers just let me know here or to discord that you would like to assign some issue so we don't collide ;)

**Comment by p53** [comment]
closing in favor of #101

**Pull request closed without merging**
